### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by gingerbeardman** [abagames/joys-of-small-game-development-en#1]
If this series will grow over time, please add RSS feed. So readers can subscribe to be alerted when new content appears. 

I believe there's a honkit/gitbook plugin https://github.com/denysdovhan/gitbook-plugin-rss

**Comment by abagames** [comment]
I have written all the content I want to at the moment, so I will consider adding RSS feed when I add more content in the future.

**Comment by gingerbeardman** [comment]
I understand.
