### ISSUE TITLE
Any chance of adding an epub or PDF?

### ISSUE THREAD

**Issue by flymaster** [abagames/joys-of-small-game-development-en#2]
Love the book, but I'd love it even more if I could easily download it to my Kindle.

**Comment by gingerbeardman** [comment]
This is easy:
1. clone repo
2. `npm install honkit`
3. `sudo ln -s /Applications/calibre.app/Contents/MacOS/ebook-convert /usr/local/bin`
4. `ebook-convert` to confirm it run and shows output
5. `npx honkit epub . ./book.epub`

More info: https://honkit.netlify.app and https://honkit.netlify.app/ebook.html

```
matt@matt ~/Projects/joys-of-small-game-development-en main !1
% npx honkit epub . ./book.epub
(node:17855) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info: 5 plugins are installed 
info: 5 explicitly listed 
info: plugin "highlight" is loaded
info: plugin "search" is loaded
info: plugin "lunr" is loaded
info: plugin "fontsettings" is loaded
info: plugin "theme-default" is loaded
info: found 25 pages 
info: found 53 asset files 
info: >> generation finished with success in 29.7s ! 
info: >> 1 file(s) generated 
matt@matt ~/Projects/joys-of-small-game-development-en main !1 ?1
% 
```

**Comment by gingerbeardman** [comment]
EPUB as of right now (11MB):
[joys-of-small-game-development-en.epub](https://www.dropbox.com/scl/fi/v57czgrtycvwf7ivbjxl0/joys-of-small-game-development-en.epub?rlkey=pg7gfrt8ik2qsqaja47j5e3q0&dl=1)

(most of the size is various animated GIF files, one of which is 7MB)

Alternate version that removes the big files and optimizes all images (1.8MB):
[joys-of-small-game-development-en.opt.epub](https://www.dropbox.com/scl/fi/jph7nx9m9phaem4bewjry/joys-of-small-game-development-en.opt.epub?rlkey=z3kpdvdow50838ojvsepa4883&dl=1)
